### ISSUE TITLE
The page 404s even though it works

### ISSUE THREAD

**Issue by adamschwartz** [HubSpot/hubstar#1]
View the console on http://adamschwartz.co/magic-of-css or see this:

![screen shot 2014-08-31 at 3 01 56 pm](https://cloud.githubusercontent.com/assets/154613/4102877/03a82b80-3141-11e4-8c4d-1b153adbda81.png)

**Comment by adamschwartz** [comment]
@zackbloom thoughts?

**Comment by zackbloom** [comment]
If it's being served from github pages, I have no idea how it would not
404.  We'd need to host it from a real host.

**Comment by adamschwartz** [comment]
Ah I see. Forgot we set it up that way.
